// Arco 图标名 → @lucide/vue 组件名映射（迁移期单一数据源）
// 用法：<Icon name="refresh" /> ；AppIcon 组件据此渲染 lucide 图标。
// 校验脚本：scripts/icon-map-check.mjs（全部键已在 @lucide/vue 中验证存在）
export const iconMap = {
  refresh: "RefreshCw",
  check: "Check",
  copy: "Copy",
  search: "Search",
  delete: "Trash2",
  apps: "LayoutGrid",
  clean: "Sparkles",
  "check-circle": "CheckCircle2",
  "check-circle-fill": "CheckCircle2",
  folder: "Folder",
  file: "FileText",
  shortcut: "Link2",
  tool: "Wrench",
  database: "Database",
  settings: "Settings",
  history: "History",
  left: "ChevronLeft",
  sync: "Repeat",
  download: "Download",
  "close-circle-fill": "XCircle",
  "info-circle": "Info",
  plus: "Plus",
  code: "Code",
  lock: "Lock",
  fire: "Flame",
  "chat-line": "MessageSquare",
  "clock-circle": "Clock",
  "bar-chart": "BarChart3",
  relation: "GitBranch",
  edit: "PenLine",
  "water-drop": "Droplet",
  export: "FileUp",
  cookie: "Cookie",
  upload: "Upload",
  save: "Save",
  eye: "Eye",
  "eye-off": "EyeOff",
  "folder-open": "FolderOpen",
  pause: "Pause",
  "play-arrow": "Play",
  "arrow-up": "ArrowUp",
  "arrow-down": "ArrowDown",
  right: "ChevronRight",
  down: "ChevronDown",
  minus: "Minus",
  "radio-button-unchecked": "Circle",
  "plus-circle": "PlusCircle",
  close: "X",
  build: "Hammer",
  tags: "Tags",
  stop: "Square",
  menu: "Menu",
  "code-square": "SquareCode",
  "exclamation-circle-fill": "CircleAlert",
  key: "KeyRound",

  // Sidebar 侧边栏动态图标
  dashboard: "LayoutDashboard",
  swap: "ArrowLeftRight",
  command: "Command",
  thunderbolt: "Zap",
  idcard: "IdCard",
  branch: "GitBranch",
  "code-block": "CodeXml",
  archive: "Archive",
  island: "Pill",
};

export const FALLBACK_ICON = "CircleAlert";