use base64::Engine as _;
use rusqlite::Connection;
use serde::{Deserialize, Serialize};
#[cfg(target_os = "linux")]
use sha2::{Digest, Sha256};
use std::path::{Path, PathBuf};

/// 前端展示的最大 Cookie 条数
const MAX_DISPLAY_COOKIES: usize = 500;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_cookie_entry_serialization() {
        let entry = CookieEntry {
            name: "session".to_string(),
            value: "abc123".to_string(),
            domain: ".example.com".to_string(),
            path: "/".to_string(),
            expires: 1700000000,
            secure: true,
            httponly: true,
        };
        let json = serde_json::to_string(&entry).unwrap();
        assert!(json.contains("\"name\":\"session\""));
        assert!(json.contains("\"domain\":\".example.com\""));
    }

    #[test]
    fn test_browser_info_serialization() {
        let info = BrowserInfo {
            name: "Chrome".to_string(),
            cookie_path: "/path/to/Cookies".to_string(),
            cookie_count: 42,
        };
        let json = serde_json::to_string(&info).unwrap();
        assert!(json.contains("\"cookie_count\":42"));
    }

    #[test]
    fn test_export_as_netscape_format() {
        let cookies = vec![
            CookieEntry {
                name: "token".to_string(),
                value: "secret".to_string(),
                domain: ".example.com".to_string(),
                path: "/".to_string(),
                expires: 2000000000,
                secure: true,
                httponly: true,
            },
            CookieEntry {
                name: "non_secure".to_string(),
                value: "val".to_string(),
                domain: ".test.com".to_string(),
                path: "/app".to_string(),
                expires: 0,
                secure: false,
                httponly: false,
            },
        ];
        let mut output = String::from("# Netscape HTTP Cookie File\n");
        output.push_str("# https://curl.haxx.se/docs/http-cookies.html\n");
        output.push_str("# This file was generated by DevNexus\n\n");
        for cookie in &cookies {
            let expires = if cookie.expires > 0 {
                cookie.expires.to_string()
            } else {
                "0".to_string()
            };
            output.push_str(&format!(
                "{}\t{}\t{}\t{}\t{}\t{}\t{}\n",
                cookie.domain,
                if cookie.httponly { "TRUE" } else { "FALSE" },
                cookie.path,
                if cookie.secure { "TRUE" } else { "FALSE" },
                expires,
                cookie.name,
                cookie.value
            ));
        }
        assert!(output.starts_with("# Netscape"));
    }

    #[test]
    fn test_infer_cookie_table_firefox() {
        let conn = Connection::open_in_memory().unwrap();
        conn.execute_batch("CREATE TABLE moz_cookies (id INTEGER);")
            .unwrap();
        let table = infer_cookie_table(&conn).unwrap();
        assert_eq!(table, "moz_cookies");
    }

    #[test]
    fn test_infer_cookie_table_chrome() {
        let conn = Connection::open_in_memory().unwrap();
        conn.execute_batch("CREATE TABLE cookies (id INTEGER);")
            .unwrap();
        let table = infer_cookie_table(&conn).unwrap();
        assert_eq!(table, "cookies");
    }

    #[test]
    fn test_infer_cookie_table_fallback() {
        let conn = Connection::open_in_memory().unwrap();
        let table = infer_cookie_table(&conn).unwrap();
        assert_eq!(table, "cookies");
    }

    #[test]
    fn test_count_cookies_fails_on_missing_db() {
        let path = PathBuf::from("/nonexistent/path/cookies.db");
        let result = count_cookies(&path);
        assert!(result.is_err());
    }

    #[test]
    fn test_map_chrome_cookie_fields() {
        let json = r#"{
            "name": "test",
            "value": "encrypted",
            "domain": ".example.com",
            "path": "/",
            "expires": 1000,
            "secure": false,
            "httponly": false
        }"#;
        let entry: CookieEntry = serde_json::from_str(json).unwrap();
        assert_eq!(entry.name, "test");
        assert_eq!(entry.expires, 1000);
        assert!(!entry.secure);
    }
}

#[derive(Serialize, Deserialize, Clone)]
pub struct CookieEntry {
    pub name: String,
    pub value: String,
    pub domain: String,
    pub path: String,
    pub expires: i64,
    pub secure: bool,
    pub httponly: bool,
}

#[derive(Serialize, Deserialize)]
pub struct BrowserInfo {
    pub name: String,
    pub cookie_path: String,
    pub cookie_count: usize,
}

/// 获取支持的浏览器列表
#[tauri::command]
pub fn get_supported_browsers() -> Vec<BrowserInfo> {
    let mut browsers = Vec::new();

    // Chrome
    if let Some(path) = get_chrome_cookie_path() {
        let count = count_cookies(&path).unwrap_or(0);
        browsers.push(BrowserInfo {
            name: "Chrome".to_string(),
            cookie_path: path.to_string_lossy().to_string(),
            cookie_count: count,
        });
    }

    // Edge
    if let Some(path) = get_edge_cookie_path() {
        let count = count_cookies(&path).unwrap_or(0);
        browsers.push(BrowserInfo {
            name: "Edge".to_string(),
            cookie_path: path.to_string_lossy().to_string(),
            cookie_count: count,
        });
    }

    // Firefox
    if let Some(path) = get_firefox_cookie_path() {
        let count = count_cookies(&path).unwrap_or(0);
        browsers.push(BrowserInfo {
            name: "Firefox".to_string(),
            cookie_path: path.to_string_lossy().to_string(),
            cookie_count: count,
        });
    }

    browsers
}

/// 提取指定浏览器的 Cookie
#[tauri::command]
pub fn extract_cookies(
    browser_name: String,
    domain_filter: Option<String>,
    max_results: Option<usize>,
) -> Result<Vec<CookieEntry>, String> {
    let cookie_path = match browser_name.as_str() {
        "Chrome" => get_chrome_cookie_path(),
        "Edge" => get_edge_cookie_path(),
        "Firefox" => get_firefox_cookie_path(),
        _ => return Err(format!("Unsupported browser: {}", browser_name)),
    };

    let path = cookie_path.ok_or_else(|| format!("{} cookie database not found", browser_name))?;

    if !path.exists() {
        return Err(format!("Cookie database does not exist: {:?}", path));
    }

    // 前端调用时 None → 默认 500 条限制，防止 IPC 数据过大导致崩溃
    let limit = max_results.unwrap_or(MAX_DISPLAY_COOKIES);
    let cookies = read_cookies(&path, domain_filter, Some(limit))?;
    Ok(cookies)
}

/// 导出为 Netscape Cookie 格式（curl/wget 兼容）
#[tauri::command]
pub fn export_as_netscape(
    browser_name: String,
    domain_filter: Option<String>,
) -> Result<String, String> {
    let path = get_browser_cookie_path(&browser_name)?;
    let cookies = read_cookies(&path, domain_filter, None)?;

    let mut output = String::from("# Netscape HTTP Cookie File\n");
    output.push_str("# https://curl.haxx.se/docs/http-cookies.html\n");
    output.push_str("# This file was generated by DevNexus\n\n");

    for cookie in cookies {
        let expires = if cookie.expires > 0 {
            cookie.expires.to_string()
        } else {
            "0".to_string()
        };

        output.push_str(&format!(
            "{}\t{}\t{}\t{}\t{}\t{}\t{}\n",
            cookie.domain,
            if cookie.httponly { "TRUE" } else { "FALSE" },
            cookie.path,
            if cookie.secure { "TRUE" } else { "FALSE" },
            expires,
            cookie.name,
            cookie.value
        ));
    }

    Ok(output)
}

/// 导出为 JSON 格式
#[tauri::command]
pub fn export_as_json(
    browser_name: String,
    domain_filter: Option<String>,
) -> Result<String, String> {
    let path = get_browser_cookie_path(&browser_name)?;
    let cookies = read_cookies(&path, domain_filter, None)?;
    serde_json::to_string_pretty(&cookies).map_err(|e| e.to_string())
}

// ==================== 浏览器 Cookie 路径检测 ====================

/// 根据浏览器名称获取 Cookie 数据库路径（供导出函数使用）
fn get_browser_cookie_path(browser_name: &str) -> Result<PathBuf, String> {
    let path = match browser_name {
        "Chrome" => get_chrome_cookie_path(),
        "Edge" => get_edge_cookie_path(),
        "Firefox" => get_firefox_cookie_path(),
        _ => return Err(format!("Unsupported browser: {}", browser_name)),
    };
    path.ok_or_else(|| format!("{} cookie database not found", browser_name))
}

fn get_chrome_cookie_path() -> Option<PathBuf> {
    #[cfg(target_os = "macos")]
    {
        if let Ok(home) = std::env::var("HOME") {
            let path = PathBuf::from(home)
                .join("Library/Application Support/Google/Chrome/Default/Cookies");
            if path.exists() {
                return Some(path);
            }
        }
    }

    #[cfg(target_os = "linux")]
    {
        if let Ok(home) = std::env::var("HOME") {
            let path = PathBuf::from(home).join(".config/google-chrome/Default/Cookies");
            if path.exists() {
                return Some(path);
            }
        }
    }

    #[cfg(target_os = "windows")]
    {
        if let Ok(localappdata) = std::env::var("LOCALAPPDATA") {
            let path = PathBuf::from(localappdata)
                .join("Google\\Chrome\\User Data\\Default\\Network\\Cookies");
            if path.exists() {
                return Some(path);
            }
        }
    }

    // 检查 Chromium
    if let Ok(ref home) = std::env::var("HOME") {
        let path = PathBuf::from(home).join(".config/chromium/Default/Cookies");
        if path.exists() {
            return Some(path);
        }
        // Snap 安装的 Chromium
        let snap_path =
            PathBuf::from(home).join("snap/chromium/current/.config/chromium/Default/Cookies");
        if snap_path.exists() {
            return Some(snap_path);
        }
    }

    None
}

fn get_edge_cookie_path() -> Option<PathBuf> {
    #[cfg(target_os = "macos")]
    {
        if let Ok(home) = std::env::var("HOME") {
            let path = PathBuf::from(home)
                .join("Library/Application Support/Microsoft Edge/Default/Cookies");
            if path.exists() {
                return Some(path);
            }
        }
    }

    #[cfg(target_os = "linux")]
    {
        if let Ok(home) = std::env::var("HOME") {
            let path = PathBuf::from(home).join(".config/microsoft-edge/Default/Cookies");
            if path.exists() {
                return Some(path);
            }
        }
    }

    #[cfg(target_os = "windows")]
    {
        if let Ok(localappdata) = std::env::var("LOCALAPPDATA") {
            let path =
                PathBuf::from(localappdata).join("Microsoft\\Edge\\User Data\\Default\\Cookies");
            if path.exists() {
                return Some(path);
            }
        }
    }

    None
}

fn get_firefox_cookie_path() -> Option<PathBuf> {
    let home = std::env::var("HOME").ok()?;
    let profile_root = PathBuf::from(&home).join(".mozilla/firefox");

    if !profile_root.exists() {
        return None;
    }

    // 读取 profiles.ini 找到默认 profile
    let profiles_ini = profile_root.join("profiles.ini");
    if profiles_ini.exists() {
        if let Ok(content) = std::fs::read_to_string(&profiles_ini) {
            let mut current_path: Option<String> = None;
            let mut is_default = false;
            for line in content.lines() {
                let line = line.trim();
                if line.to_lowercase() == "[profile0]" || line.starts_with("[profile") {
                    current_path = None;
                    is_default = false;
                } else if let Some(val) = line.strip_prefix("Path=") {
                    current_path = Some(val.to_string());
                } else if line.to_lowercase() == "default=1" || line.starts_with("Default=") {
                    is_default = true;
                }
                // Section break — evaluate
                if line.is_empty() || (line.starts_with('[') && current_path.is_some()) {
                    if is_default {
                        if let Some(ref path) = current_path {
                            let cookie_path = if path.starts_with('/') {
                                PathBuf::from(path)
                            } else {
                                profile_root.join(path)
                            }
                            .join("cookies.sqlite");
                            if cookie_path.exists() {
                                return Some(cookie_path);
                            }
                        }
                    }
                    if line.starts_with('[') && line != "[Profile0]" {
                        current_path = None;
                        is_default = false;
                    }
                }
            }
            // Check last section
            if is_default {
                if let Some(ref path) = current_path {
                    let cookie_path = if path.starts_with('/') {
                        PathBuf::from(path)
                    } else {
                        profile_root.join(path)
                    }
                    .join("cookies.sqlite");
                    if cookie_path.exists() {
                        return Some(cookie_path);
                    }
                }
            }
        }
    }

    // 回退：扫描 profile 目录
    if let Ok(entries) = std::fs::read_dir(&profile_root) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                let cookie_path = path.join("cookies.sqlite");
                if cookie_path.exists() {
                    return Some(cookie_path);
                }
            }
        }
    }

    None
}

// ==================== Cookie 数据库操作 ====================

fn count_cookies(path: &PathBuf) -> Result<usize, String> {
    let conn = Connection::open(path).map_err(|e| format!("Failed to open: {}", e))?;
    let table = infer_cookie_table(&conn)?;
    let count: usize = conn
        .query_row(&format!("SELECT COUNT(*) FROM {}", table), [], |row| {
            row.get(0)
        })
        .map_err(|e| format!("Count failed: {}", e))?;
    Ok(count)
}

fn infer_cookie_table(conn: &Connection) -> Result<&'static str, String> {
    let tables: Vec<String> = conn
        .prepare("SELECT name FROM sqlite_master WHERE type='table'")
        .map_err(|e| format!("Query failed: {}", e))?
        .query_map([], |row| row.get(0))
        .map_err(|e| format!("Query failed: {}", e))?
        .filter_map(|r| r.ok())
        .collect();

    if tables.iter().any(|t| t == "moz_cookies") {
        Ok("moz_cookies")
    } else {
        Ok("cookies")
    }
}

/// 获取 Cookie 数据库的版本号（用于判断是否包含完整性检查哈希）
fn get_cookie_db_version(path: &Path) -> i32 {
    if let Ok(conn) = Connection::open(path) {
        if let Ok(version) =
            conn.query_row("SELECT value FROM meta WHERE key='version'", [], |row| {
                row.get::<_, i32>(0)
            })
        {
            return version;
        }
    }
    0
}

fn map_chrome_cookie_row(
    row: &rusqlite::Row,
    has_integrity_check: bool,
) -> rusqlite::Result<CookieEntry> {
    let encrypted_value: Vec<u8> = row.get(1)?;
    let host_key: String = row.get(2)?;
    let expires_utc: i64 = row.get(4)?;
    // Chrome 的 expires_utc 是微秒（microseconds）从 1601-01-01（WebKit epoch）
    // 转换为 Unix 秒数（从 1970-01-01）
    // 偏移量：11644473600 秒（1601 → 1970），微秒 → 秒 ÷ 1_000_000
    let expires = if expires_utc == 0 {
        0 // session cookie
    } else {
        let unix_micros = expires_utc - 11_644_473_600_000_000i64;
        let unix_secs = unix_micros / 1_000_000;
        if unix_secs > 0 {
            unix_secs
        } else {
            0
        }
    };
    Ok(CookieEntry {
        name: row.get(0)?,
        value: decrypt_cookie_value(&encrypted_value, &host_key, has_integrity_check),
        domain: host_key,
        path: row.get(3)?,
        expires,
        secure: row.get(5)?,
        httponly: row.get(6)?,
    })
}

fn map_firefox_cookie_row(row: &rusqlite::Row) -> rusqlite::Result<CookieEntry> {
    let value: String = row.get(1)?;
    Ok(CookieEntry {
        name: row.get(0)?,
        value,
        domain: row.get(2)?,
        path: row.get(3)?,
        expires: row.get(4)?,
        secure: row.get(5)?,
        httponly: row.get(6)?,
    })
}

fn read_cookies(
    path: &PathBuf,
    domain_filter: Option<String>,
    max_results: Option<usize>,
) -> Result<Vec<CookieEntry>, String> {
    // 复制到临时文件再打开，避免浏览器锁定数据库导致 "database is locked"
    let tmp_dir = std::env::temp_dir().join("devnexus_cookies");
    let _ = std::fs::create_dir_all(&tmp_dir);
    let tmp_path = tmp_dir.join(format!("cookies_{}.sqlite", std::process::id()));
    // 删除残留文件
    let _ = std::fs::remove_file(&tmp_path);
    let _ = std::fs::remove_file(tmp_path.with_extension("sqlite-wal"));
    let _ = std::fs::remove_file(tmp_path.with_extension("sqlite-shm"));
    let _ = std::fs::remove_file(tmp_path.with_extension("sqlite-journal"));

    std::fs::copy(path, &tmp_path)
        .map_err(|e| format!("Failed to copy cookie database: {} (path: {:?})", e, path))?;

    // 复制 SQLite 辅助文件（WAL 或 journal 模式），保证数据一致性
    // Chrome 实际辅助文件格式: Cookies-wal, Cookies-shm, Cookies-journal（拼接后缀，非替换扩展名）
    if let (Some(parent), Some(filename)) = (path.parent(), path.file_name()) {
        let fname = filename.to_string_lossy();

        // WAL 模式: Cookies-wal, Cookies-shm
        let wal_path = parent.join(format!("{}-wal", fname));
        if wal_path.exists() {
            let _ = std::fs::copy(&wal_path, tmp_path.with_extension("sqlite-wal"));
            let shm_path = parent.join(format!("{}-shm", fname));
            if shm_path.exists() {
                let _ = std::fs::copy(&shm_path, tmp_path.with_extension("sqlite-shm"));
            }
        }

        // Journal 模式: Cookies-journal
        let journal_path = parent.join(format!("{}-journal", fname));
        if journal_path.exists() {
            let _ = std::fs::copy(&journal_path, tmp_path.with_extension("sqlite-journal"));
        }
    }

    // 判断是否需要完整性检查（数据库版本 >= 24 表示有 v11 格式的完整性检查）
    // 从临时副本读取版本，避免浏览器锁定原库
    let has_integrity_check = get_cookie_db_version(&tmp_path) >= 24;

    let conn =
        Connection::open(&tmp_path).map_err(|e| format!("Failed to open database: {}", e))?;
    let table = infer_cookie_table(&conn)?;

    // 根据 max_results 生成 LIMIT 子句
    let limit_clause = match max_results {
        Some(n) => format!(" LIMIT {}", n),
        None => String::new(),
    };

    let (query, param) = if table == "moz_cookies" {
        let base = "SELECT name, value, host, path, expiry, isSecure, isHttpOnly FROM moz_cookies";
        match domain_filter {
            Some(ref domain) => (
                format!("{} WHERE host LIKE ?1{}", base, limit_clause),
                Some(format!("%{}%", domain)),
            ),
            None => (format!("{}{}", base, limit_clause), None),
        }
    } else {
        let base = "SELECT name, encrypted_value, host_key, path, expires_utc, is_secure, is_httponly FROM cookies";
        match domain_filter {
            Some(ref domain) => (
                format!("{} WHERE host_key LIKE ?1{}", base, limit_clause),
                Some(format!("%{}%", domain)),
            ),
            None => (format!("{}{}", base, limit_clause), None),
        }
    };

    let mut stmt = conn
        .prepare(&query)
        .map_err(|e| format!("Prepare failed: {}", e))?;

    let mut cookies = Vec::new();

    if table == "moz_cookies" {
        let map_fn = map_firefox_cookie_row;
        if let Some(ref p) = param {
            let mut rows = stmt
                .query_map([p.as_str()], map_fn)
                .map_err(|e| format!("Query failed: {}", e))?;
            while let Some(Ok(c)) = rows.next() {
                cookies.push(c);
            }
        } else {
            let mut rows = stmt
                .query_map([], map_fn)
                .map_err(|e| format!("Query failed: {}", e))?;
            while let Some(Ok(c)) = rows.next() {
                cookies.push(c);
            }
        }
    } else {
        // Chrome/Edge — 传递 has_integrity_check 到 map 闭包
        if let Some(ref p) = param {
            let mut rows = stmt
                .query_map([p.as_str()], |row| {
                    map_chrome_cookie_row(row, has_integrity_check)
                })
                .map_err(|e| format!("Query failed: {}", e))?;
            while let Some(Ok(c)) = rows.next() {
                cookies.push(c);
            }
        } else {
            let mut rows = stmt
                .query_map([], |row| map_chrome_cookie_row(row, has_integrity_check))
                .map_err(|e| format!("Query failed: {}", e))?;
            while let Some(Ok(c)) = rows.next() {
                cookies.push(c);
            }
        }
    }

    Ok(cookies)
}

// ==================== Chrome Cookie 解密核心逻辑 ====================

/// 解密 Chrome 加密的 Cookie 值
///
/// 解密规则（Linux）:
/// - v10/v11 前缀（3字节）
/// - AES-128-CBC 加密，IV = 16个空格（0x20）
/// - 密钥: PBKDF2(SecretService 密码, "saltysalt", 1, 16)
/// - v11 + DB version >= 24: 密文解密后前32字节是 SHA256(host) 完整性校验
fn decrypt_cookie_value(encrypted: &[u8], host_key: &str, has_integrity_check: bool) -> String {
    if encrypted.len() < 3 {
        return String::from_utf8_lossy(encrypted).to_string();
    }

    if &encrypted[0..3] == b"v10" || &encrypted[0..3] == b"v11" {
        return decrypt_chrome_v10(&encrypted[3..], host_key, has_integrity_check);
    }

    // 未加密（旧版本或非 Chrome 浏览器）
    String::from_utf8_lossy(encrypted).to_string()
}

/// Chrome v10+ 解密（AES-256-GCM 或 AES-128-CBC，取决于平台）
#[cfg(any(target_os = "macos", target_os = "windows"))]
fn decrypt_chrome_v10(encrypted_data: &[u8], _host_key: &str, has_integrity_check: bool) -> String {
    use aes_gcm::{
        aead::{Aead, KeyInit},
        Aes256Gcm, Nonce,
    };

    let key32 = match get_chrome_encryption_key_v10() {
        Some(k) => k,
        None => return "[Failed to get Chrome encryption key]".to_string(),
    };

    let cipher = match Aes256Gcm::new_from_slice(&key32) {
        Ok(c) => c,
        Err(_) => return "[Invalid key]".to_string(),
    };

    // v11 格式前面有 16 字节认证标签/header，需要跳过
    let offset = if has_integrity_check { 16 } else { 0 };

    // AES-256-GCM: nonce 12 字节 + tag 至少 16 字节
    if encrypted_data.len() < offset + 12 + 16 {
        return String::from_utf8_lossy(encrypted_data).to_string();
    }

    let nonce = Nonce::from_slice(&encrypted_data[offset..offset + 12]);
    let ciphertext = &encrypted_data[offset + 12..];

    match cipher.decrypt(nonce, ciphertext) {
        Ok(pt) => String::from_utf8_lossy(&pt).to_string(),
        Err(_) => "[Cookie decryption failed]".to_string(),
    }
}

/// Linux 上 Chrome 使用 AES-128-CBC 加密 Cookie
///
/// 数据格式（v11 前缀已去除）：
///   - bytes [0..16): 认证标签/header（跳过）
///   - bytes [16..32): 随机 IV（16 字节）
///   - bytes [32..): AES-128-CBC 密文
///
/// 密钥通过 Secret Service (D-Bus) 获取后由 PBKDF2 派生
#[cfg(target_os = "linux")]
fn decrypt_chrome_v10(encrypted_data: &[u8], host_key: &str, has_integrity_check: bool) -> String {
    let v11_key = match get_chrome_encryption_key_v10() {
        Some(k) => k,
        None => {
            return decrypt_chrome_v10_fallback(encrypted_data);
        }
    };

    // 需要至少 48 字节: 16(auth) + 16(IV) + 16(最小密文)
    if encrypted_data.len() < 48 {
        return String::from_utf8_lossy(encrypted_data).to_string();
    }

    // 标准格式: auth_tag[16] + iv[16] + ciphertext
    let result1 = try_aes_128_cbc(
        &v11_key,
        &encrypted_data[16..32],
        &encrypted_data[32..],
        host_key,
        has_integrity_check,
    );
    if !result1.starts_with('[') {
        return result1;
    }

    // 回退: 固定 IV (16个空格)，整个数据作为密文
    let fixed_iv = [0x20u8; 16];
    let result2 = try_aes_128_cbc(
        &v11_key,
        &fixed_iv,
        encrypted_data,
        host_key,
        has_integrity_check,
    );
    if !result2.starts_with('[') {
        return result2;
    }

    // 所有解密尝试都失败，返回第一个错误（更简洁的反馈）
    result1
}

/// 尝试 AES-128-CBC 解密
#[cfg(target_os = "linux")]
fn try_aes_128_cbc(
    key: &[u8; 16],
    iv: &[u8],
    ciphertext: &[u8],
    host_key: &str,
    has_integrity_check: bool,
) -> String {
    use aes::cipher::{BlockDecryptMut, KeyIvInit};
    type Aes128CbcDec = cbc::Decryptor<aes::Aes128>;

    if ciphertext.is_empty() {
        return "[Empty ciphertext]".to_string();
    }

    let dec = match Aes128CbcDec::new_from_slices(key, iv) {
        Ok(d) => d,
        Err(e) => return format!("[CBC init error: {}]", e),
    };

    let mut buf = ciphertext.to_vec();
    dec.decrypt_padded_mut::<aes::cipher::block_padding::Pkcs7>(&mut buf)
        .map(|plaintext| {
            if has_integrity_check {
                if plaintext.len() > 32 {
                    let _integrity_hash = &plaintext[..32];
                    let _expected_hash = Sha256::digest(host_key.as_bytes());
                    String::from_utf8_lossy(&plaintext[32..]).to_string()
                } else {
                    String::from_utf8_lossy(plaintext).to_string()
                }
            } else {
                String::from_utf8_lossy(plaintext).to_string()
            }
        })
        .unwrap_or_else(|e| format!("[Decrypt fail: {}]", e))
}

/// Linux 回退：尝试用 AES-256-GCM 解密（旧版 Chrome < v127）
#[cfg(target_os = "linux")]
fn decrypt_chrome_v10_fallback(encrypted_data: &[u8]) -> String {
    use aes_gcm::{
        aead::{Aead, KeyInit},
        Aes256Gcm, Nonce,
    };

    // 如果缺少 encrypted_key 字段，返回失败
    if encrypted_data.len() < 12 + 16 {
        return String::from_utf8_lossy(encrypted_data).to_string();
    }

    // 尝试从 keyring 获取旧版密钥
    // 使用硬编码的 fallback: 某些旧 Chrome 版本密钥是固定的
    // 更多的 fallback 方式留给 get_chrome_encryption_key_v10 处理
    match get_chrome_encryption_key_v10_fallback() {
        Some(key32) => {
            let cipher = match Aes256Gcm::new_from_slice(&key32) {
                Ok(c) => c,
                Err(_) => return "[Invalid key (fallback)]".to_string(),
            };
            let nonce = Nonce::from_slice(&encrypted_data[0..12]);
            let ciphertext = &encrypted_data[12..];
            match cipher.decrypt(nonce, ciphertext) {
                Ok(pt) => String::from_utf8_lossy(&pt).to_string(),
                Err(_) => "[Fallback decrypt failed]".to_string(),
            }
        }
        None => "[No Chrome encryption key found (Linux)]".to_string(),
    }
}

// ==================== Chrome 加密密钥获取 ====================

/// macOS: 通过 Keychain 获取 Chrome v10+ AES-256-GCM 加密密钥
#[cfg(target_os = "macos")]
fn get_chrome_encryption_key_v10() -> Option<[u8; 32]> {
    use keyring::Entry;
    let entry = Entry::new("Chrome Safe Storage", "Chrome").ok()?;
    let password = entry.get_password().ok()?;
    // macOS 上密码是 base64 编码的 32 字节密钥
    if password.len() == 32 {
        let mut key = [0u8; 32];
        key.copy_from_slice(password.as_bytes());
        return Some(key);
    }
    // 也可能是 base64 编码的
    if let Ok(decoded) = base64::engine::general_purpose::STANDARD.decode(&password) {
        if decoded.len() == 32 {
            let mut key = [0u8; 32];
            key.copy_from_slice(&decoded);
            return Some(key);
        }
    }
    // 回退：尝试直接使用密码的字节
    let bytes = password.as_bytes();
    if bytes.len() >= 32 {
        let mut key = [0u8; 32];
        key.copy_from_slice(&bytes[0..32]);
        return Some(key);
    }
    None
}

/// Linux: 通过 Secret Service 获取 Chrome 加密密钥（v11 AES-128-CBC）
///
/// 尝试多种方式获取，按优先级：
/// 1. secret-tool CLI（无额外依赖）
/// 2. Rust D-Bus 直接访问
/// 3. Python dbus-python（回退）
#[cfg(target_os = "linux")]
fn get_chrome_encryption_key_v10() -> Option<[u8; 16]> {
    // 方法1: 使用 secret-tool CLI
    if let Some(key) = try_secret_tool_v11() {
        return Some(key);
    }

    // 方法2: 使用 Rust D-Bus
    if let Some(key) = try_dbus_rust() {
        return Some(key);
    }

    // 方法3: 使用 Python dbus-python（最后的回退）
    try_dbus_python()
}

/// 通过 secret-tool CLI 获取 Chrome v11 密钥
#[cfg(target_os = "linux")]
fn try_secret_tool_v11() -> Option<[u8; 16]> {
    let output = std::process::Command::new("secret-tool")
        .args([
            "search",
            "--all",
            "xdg:schema",
            "chrome_libsecret_os_crypt_password_v2",
            "application",
            "chrome",
        ])
        .output()
        .ok()?;

    if !output.status.success() {
        return None;
    }

    let stdout = String::from_utf8_lossy(&output.stdout);
    for line in stdout.lines() {
        let line = line.trim();
        if let Some(value) = line.strip_prefix("secret = ") {
            let pwd = value.trim().to_string();
            if !pwd.is_empty() {
                return derive_v11_key_from_str(&pwd);
            }
        }
    }
    None
}

/// 从密码字符串派生 v11 密钥
/// 注意：Chromium 直接将 base64 编码的密钥字符串（不解码）作为 PBKDF2 的 password 输入
#[cfg(target_os = "linux")]
fn derive_v11_key_from_str(secret_str: &str) -> Option<[u8; 16]> {
    let secret_str = secret_str.trim();
    if secret_str.is_empty() {
        return None;
    }

    // 直接使用原始字符串的 ASCII 字节作为 PBKDF2 输入（不要 base64 解码）
    use pbkdf2::pbkdf2_hmac;
    use sha1::Sha1;
    let mut key = [0u8; 16];
    pbkdf2_hmac::<Sha1>(secret_str.as_bytes(), b"saltysalt", 1, &mut key);
    Some(key)
}

/// 使用 Rust dbus crate 直接访问 Secret Service
#[cfg(target_os = "linux")]
fn try_dbus_rust() -> Option<[u8; 16]> {
    use dbus::{
        blocking::{BlockingSender, Connection},
        Message,
    };
    use std::collections::HashMap;
    use std::time::Duration;

    let conn = Connection::new_session().ok()?;

    let mut search_attrs = HashMap::new();
    search_attrs.insert(
        "xdg:schema".to_string(),
        "chrome_libsecret_os_crypt_password_v2".to_string(),
    );
    search_attrs.insert("application".to_string(), "chrome".to_string());

    let timeout = Duration::from_secs(3);

    let r = conn
        .send_with_reply_and_block(
            Message::new_method_call(
                "org.freedesktop.secrets",
                "/org/freedesktop/secrets",
                "org.freedesktop.Secret.Service",
                "SearchItems",
            )
            .ok()?
            .append1(search_attrs),
            timeout,
        )
        .ok()?;
    let (items, _prompt): (Vec<dbus::Path<'static>>, dbus::Path<'static>) = r.read2().ok()?;
    let item_path = items.first()?.clone();

    let _ = conn.send_with_reply_and_block(
        Message::new_method_call(
            "org.freedesktop.secrets",
            "/org/freedesktop/secrets",
            "org.freedesktop.Secret.Service",
            "Unlock",
        )
        .ok()?
        .append1(vec![item_path.clone()]),
        timeout,
    );

    let session_path = {
        let r = conn
            .send_with_reply_and_block(
                Message::new_method_call(
                    "org.freedesktop.secrets",
                    "/org/freedesktop/secrets",
                    "org.freedesktop.Secret.Service",
                    "OpenSession",
                )
                .ok()?
                .append2("plain", dbus::arg::Variant(Box::new(String::new()))),
                timeout,
            )
            .ok()?;
        let (result, session): (
            dbus::arg::Variant<Box<dyn dbus::arg::RefArg>>,
            dbus::Path<'static>,
        ) = r.read2().ok()?;
        drop(result);
        session
    };

    let secret_value = {
        let r = conn
            .send_with_reply_and_block(
                Message::new_method_call(
                    "org.freedesktop.secrets",
                    "/org/freedesktop/secrets",
                    "org.freedesktop.Secret.Service",
                    "GetSecrets",
                )
                .ok()?
                .append2(vec![item_path], session_path),
                timeout,
            )
            .ok()?;

        use dbus::arg::ArgType;
        let mut iter = r.iter_init();
        {
            let mut array_iter = iter.recurse(ArgType::Array)?;
            let mut found_value: Option<Vec<u8>> = None;
            while let Some(mut entry_iter) = array_iter.recurse(ArgType::DictEntry) {
                let _key: dbus::Path<'static> = entry_iter.read().ok()?;
                if let Some(mut struct_iter) = entry_iter.recurse(ArgType::Struct) {
                    let _sess: dbus::Path<'static> = struct_iter.read().ok()?;
                    let value: Vec<u8> = struct_iter.read().ok()?;
                    let _content_type: String = struct_iter.read().ok()?;
                    let _parameters: Vec<u8> = struct_iter.read().ok()?;
                    found_value = Some(value);
                }
            }
            found_value?
        }
    };

    derive_v11_key(&secret_value)
}

/// 使用 Python dbus-python 获取 Chrome 加密密钥（最后的回退方案）
#[cfg(target_os = "linux")]
fn try_dbus_python() -> Option<[u8; 16]> {
    let script = r#"
import dbus, sys
bus = dbus.SessionBus()
ss = dbus.Interface(bus.get_object('org.freedesktop.secrets', '/org/freedesktop/secrets'), 'org.freedesktop.Secret.Service')
paths = ss.SearchItems({'xdg:schema': 'chrome_libsecret_os_crypt_password_v2', 'application': 'chrome'})
paths = [p for p in paths if p]
if not paths or not paths[0]:
    sys.exit(1)
obj_path = paths[0][0]
ss.Unlock([obj_path])
_, session = ss.OpenSession('plain', dbus.String('', variant_level=1))
secrets = ss.GetSecrets([obj_path], session)
_, _, value, _ = secrets[obj_path]
sys.stdout.buffer.write(bytes(value))
"#;

    for python_cmd in &["python3", "python"] {
        let output = std::process::Command::new(python_cmd)
            .arg("-c")
            .arg(script)
            .output()
            .ok()?;
        if output.status.success() && !output.stdout.is_empty() {
            return derive_v11_key(&output.stdout);
        }
    }
    None
}

/// 从 Secret Service 获取的原始密码派生 v11 AES-128-CBC 密钥
/// 注意：Chromium 直接将 base64 编码的密钥字符串（不解码）作为 PBKDF2 的 password 输入
#[cfg(target_os = "linux")]
fn derive_v11_key(secret_bytes: &[u8]) -> Option<[u8; 16]> {
    if secret_bytes.is_empty() {
        return None;
    }
    // Secret Service 返回的 secret 是 base64 编码的密码字符串（如 "+kOD1Z0EvL5YjX/9nfyoYA=="）
    let secret_str = std::str::from_utf8(secret_bytes).ok()?.trim();
    if secret_str.is_empty() {
        return None;
    }

    // 直接使用原始 ASCII 字节作为 PBKDF2 输入（不要 base64 解码）
    // PBKDF2-HMAC-SHA1(pwd, "saltysalt", 1, 16) -> v11_key
    use pbkdf2::pbkdf2_hmac;
    use sha1::Sha1;
    let mut key = [0u8; 16];
    pbkdf2_hmac::<Sha1>(secret_str.as_bytes(), b"saltysalt", 1, &mut key);
    Some(key)
}

/// Linux 回退方式：尝试通过其他方式获取旧版 Chrome 的 AES-256-GCM 密钥
#[cfg(target_os = "linux")]
fn get_chrome_encryption_key_v10_fallback() -> Option<[u8; 32]> {
    // 方法1: 使用 secret-tool CLI（可能需要手动解锁）
    let output = std::process::Command::new("secret-tool")
        .args(["lookup", "application", "chrome"])
        .output()
        .ok()?;
    if output.status.success() {
        let value = String::from_utf8_lossy(&output.stdout).trim().to_string();
        if !value.is_empty() {
            // secret-tool 返回的是 base64 编码的 32 字节密钥
            if let Ok(decoded) = base64::engine::general_purpose::STANDARD.decode(&value) {
                if decoded.len() == 32 {
                    let mut key = [0u8; 32];
                    key.copy_from_slice(&decoded);
                    return Some(key);
                }
            }
        }
    }

    // 方法2: 尝试搜索不同的 schema
    let output = std::process::Command::new("secret-tool")
        .args(["search", "application", "chrome"])
        .output()
        .ok()?;
    if output.status.success() {
        let stdout = String::from_utf8_lossy(&output.stdout);
        for line in stdout.lines() {
            if let Some(value) = line.strip_prefix("secret = ") {
                if let Ok(decoded) = base64::engine::general_purpose::STANDARD.decode(value.trim())
                {
                    if decoded.len() == 32 {
                        let mut key = [0u8; 32];
                        key.copy_from_slice(&decoded);
                        return Some(key);
                    }
                }
            }
        }
    }

    None
}

/// Windows: 通过 DPAPI 解密 Chrome Local State 中的加密密钥
#[cfg(target_os = "windows")]
fn get_chrome_encryption_key_v10() -> Option<[u8; 32]> {
    if let Ok(localappdata) = std::env::var("LOCALAPPDATA") {
        let local_state_path =
            PathBuf::from(localappdata).join("Google\\Chrome\\User Data\\Local State");

        if let Ok(content) = std::fs::read_to_string(&local_state_path) {
            if let Ok(json) = serde_json::from_str::<serde_json::Value>(&content) {
                if let Some(encoded_key) = json["os_crypt"]["encrypted_key"].as_str() {
                    if let Ok(decoded) =
                        base64::engine::general_purpose::STANDARD.decode(encoded_key)
                    {
                        if decoded.len() >= 5 && &decoded[0..5] == b"DPAPI" {
                            let raw_key = decrypt_windows_raw(&decoded[5..]);
                            if raw_key.len() >= 32 {
                                let mut key = [0u8; 32];
                                key.copy_from_slice(&raw_key[0..32]);
                                return Some(key);
                            }
                        }
                    }
                }
            }
        }
    }
    None
}

#[cfg(target_os = "windows")]
fn decrypt_windows_raw(encrypted_data: &[u8]) -> Vec<u8> {
    use windows::Win32::Security::Cryptography::{
        CryptUnprotectData, CRYPTPROTECT_UI_FORBIDDEN, CRYPT_INTEGER_BLOB,
    };

    unsafe {
        let data_in = CRYPT_INTEGER_BLOB {
            cbData: encrypted_data.len() as u32,
            pbData: encrypted_data.as_ptr() as *mut u8,
        };

        let mut data_out = CRYPT_INTEGER_BLOB {
            cbData: 0,
            pbData: std::ptr::null_mut(),
        };

        match CryptUnprotectData(
            &data_in,
            None,
            None,
            None,
            None,
            CRYPTPROTECT_UI_FORBIDDEN,
            &mut data_out as *mut _,
        ) {
            Ok(()) => {
                if data_out.pbData.is_null() || data_out.cbData == 0 {
                    return encrypted_data.to_vec();
                }
                std::slice::from_raw_parts(data_out.pbData, data_out.cbData as usize).to_vec()
            }
            Err(_) => encrypted_data.to_vec(),
        }
    }
}
