use rusqlite::Connection;
use serde::{Deserialize, Serialize};
use std::path::PathBuf;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_cookie_entry_serialization() {
        let entry = CookieEntry {
            name: "session".to_string(),
            value: "abc123".to_string(),
            domain: ".example.com".to_string(),
            path: "/".to_string(),
            expires: 1700000000,
            secure: true,
            httponly: true,
        };
        let json = serde_json::to_string(&entry).unwrap();
        assert!(json.contains("\"name\":\"session\""));
        assert!(json.contains("\"domain\":\".example.com\""));
        assert!(json.contains("\"secure\":true"));
    }

    #[test]
    fn test_browser_info_serialization() {
        let info = BrowserInfo {
            name: "Chrome".to_string(),
            cookie_path: "/path/to/Cookies".to_string(),
            cookie_count: 42,
        };
        let json = serde_json::to_string(&info).unwrap();
        assert!(json.contains("\"cookie_count\":42"));
    }

    #[test]
    fn test_export_as_netscape_format() {
        let cookies = vec![
            CookieEntry {
                name: "token".to_string(),
                value: "secret".to_string(),
                domain: ".example.com".to_string(),
                path: "/".to_string(),
                expires: 2000000000,
                secure: true,
                httponly: true,
            },
            CookieEntry {
                name: "non_secure".to_string(),
                value: "val".to_string(),
                domain: ".test.com".to_string(),
                path: "/app".to_string(),
                expires: 0,
                secure: false,
                httponly: false,
            },
        ];

        let mut output = String::from("# Netscape HTTP Cookie File\n");
        output.push_str("# https://curl.haxx.se/docs/http-cookies.html\n");
        output.push_str("# This file was generated by DevNexus\n\n");

        for cookie in &cookies {
            let expires = if cookie.expires > 0 {
                cookie.expires.to_string()
            } else {
                "0".to_string()
            };
            output.push_str(&format!(
                "{}\t{}\t{}\t{}\t{}\t{}\t{}\n",
                cookie.domain,
                if cookie.httponly { "TRUE" } else { "FALSE" },
                cookie.path,
                if cookie.secure { "TRUE" } else { "FALSE" },
                expires,
                cookie.name,
                cookie.value
            ));
        }

        assert!(output.starts_with("# Netscape"));
        assert!(output.contains(".example.com\tTRUE\t/\tTRUE\t2000000000\ttoken\tsecret"));
        assert!(output.contains(".test.com\tFALSE\t/app\tFALSE\t0\tnon_secure\tval"));
    }

    #[test]
    fn test_infer_cookie_table_firefox() {
        let conn = Connection::open_in_memory().unwrap();
        conn.execute_batch("CREATE TABLE moz_cookies (id INTEGER);")
            .unwrap();
        let table = infer_cookie_table(&conn).unwrap();
        assert_eq!(table, "moz_cookies");
    }

    #[test]
    fn test_infer_cookie_table_chrome() {
        let conn = Connection::open_in_memory().unwrap();
        conn.execute_batch("CREATE TABLE cookies (id INTEGER);")
            .unwrap();
        let table = infer_cookie_table(&conn).unwrap();
        assert_eq!(table, "cookies");
    }

    #[test]
    fn test_infer_cookie_table_fallback() {
        let conn = Connection::open_in_memory().unwrap();
        // No tables at all
        let table = infer_cookie_table(&conn).unwrap();
        assert_eq!(table, "cookies");
    }

    #[test]
    fn test_count_cookies_fails_on_missing_db() {
        let path = PathBuf::from("/nonexistent/path/cookies.db");
        let result = count_cookies(&path);
        assert!(result.is_err());
    }

    #[test]
    fn test_map_chrome_cookie_fields() {
        let json = r#"{
            "name": "test",
            "value": "encrypted",
            "domain": ".example.com",
            "path": "/",
            "expires": 1000,
            "secure": false,
            "httponly": false
        }"#;
        let entry: CookieEntry = serde_json::from_str(json).unwrap();
        assert_eq!(entry.name, "test");
        assert_eq!(entry.expires, 1000);
        assert!(!entry.secure);
    }
}

#[derive(Serialize, Deserialize, Clone)]
pub struct CookieEntry {
    pub name: String,
    pub value: String,
    pub domain: String,
    pub path: String,
    pub expires: i64,
    pub secure: bool,
    pub httponly: bool,
}

#[derive(Serialize, Deserialize)]
pub struct BrowserInfo {
    pub name: String,
    pub cookie_path: String,
    pub cookie_count: usize,
}

/// 获取支持的浏览器列表
#[tauri::command]
pub fn get_supported_browsers() -> Vec<BrowserInfo> {
    let mut browsers = Vec::new();

    // Chrome
    if let Some(path) = get_chrome_cookie_path() {
        let count = count_cookies(&path).unwrap_or(0);
        browsers.push(BrowserInfo {
            name: "Chrome".to_string(),
            cookie_path: path.to_string_lossy().to_string(),
            cookie_count: count,
        });
    }

    // Edge
    if let Some(path) = get_edge_cookie_path() {
        let count = count_cookies(&path).unwrap_or(0);
        browsers.push(BrowserInfo {
            name: "Edge".to_string(),
            cookie_path: path.to_string_lossy().to_string(),
            cookie_count: count,
        });
    }

    // Firefox
    if let Some(path) = get_firefox_cookie_path() {
        let count = count_cookies(&path).unwrap_or(0);
        browsers.push(BrowserInfo {
            name: "Firefox".to_string(),
            cookie_path: path.to_string_lossy().to_string(),
            cookie_count: count,
        });
    }

    browsers
}

/// 提取指定浏览器的 Cookie
#[tauri::command]
pub fn extract_cookies(
    browser_name: String,
    domain_filter: Option<String>,
) -> Result<Vec<CookieEntry>, String> {
    let cookie_path = match browser_name.as_str() {
        "Chrome" => get_chrome_cookie_path(),
        "Edge" => get_edge_cookie_path(),
        "Firefox" => get_firefox_cookie_path(),
        _ => return Err(format!("Unsupported browser: {}", browser_name)),
    };

    let path = cookie_path.ok_or_else(|| format!("{} cookie database not found", browser_name))?;

    if !path.exists() {
        return Err(format!("Cookie database does not exist: {:?}", path));
    }

    let cookies = read_cookies(&path, domain_filter)?;
    Ok(cookies)
}

/// 导出为 Netscape Cookie 格式（curl/wget 兼容）
#[tauri::command]
pub fn export_as_netscape(
    browser_name: String,
    domain_filter: Option<String>,
) -> Result<String, String> {
    let cookies = extract_cookies(browser_name, domain_filter)?;

    let mut output = String::from("# Netscape HTTP Cookie File\n");
    output.push_str("# https://curl.haxx.se/docs/http-cookies.html\n");
    output.push_str("# This file was generated by DevNexus\n\n");

    for cookie in cookies {
        let expires = if cookie.expires > 0 {
            cookie.expires.to_string()
        } else {
            "0".to_string()
        };

        output.push_str(&format!(
            "{}\t{}\t{}\t{}\t{}\t{}\t{}\n",
            cookie.domain,
            if cookie.httponly { "TRUE" } else { "FALSE" },
            cookie.path,
            if cookie.secure { "TRUE" } else { "FALSE" },
            expires,
            cookie.name,
            cookie.value
        ));
    }

    Ok(output)
}

/// 导出为 JSON 格式
#[tauri::command]
pub fn export_as_json(
    browser_name: String,
    domain_filter: Option<String>,
) -> Result<String, String> {
    let cookies = extract_cookies(browser_name, domain_filter)?;
    serde_json::to_string_pretty(&cookies).map_err(|e| e.to_string())
}

// ==================== 浏览器 Cookie 路径检测 ====================

fn get_chrome_cookie_path() -> Option<PathBuf> {
    #[cfg(target_os = "macos")]
    {
        if let Ok(home) = std::env::var("HOME") {
            let path = PathBuf::from(home)
                .join("Library/Application Support/Google/Chrome/Default/Cookies");
            if path.exists() {
                return Some(path);
            }
        }
    }

    #[cfg(target_os = "linux")]
    {
        if let Ok(home) = std::env::var("HOME") {
            let path = PathBuf::from(home).join(".config/google-chrome/Default/Cookies");
            if path.exists() {
                return Some(path);
            }
        }
    }

    #[cfg(target_os = "windows")]
    {
        if let Ok(localappdata) = std::env::var("LOCALAPPDATA") {
            let path = PathBuf::from(localappdata)
                .join("Google\\Chrome\\User Data\\Default\\Network\\Cookies");
            if path.exists() {
                return Some(path);
            }
        }
    }

    None
}

fn get_edge_cookie_path() -> Option<PathBuf> {
    #[cfg(target_os = "macos")]
    {
        if let Ok(home) = std::env::var("HOME") {
            let path = PathBuf::from(home)
                .join("Library/Application Support/Microsoft Edge/Default/Cookies");
            if path.exists() {
                return Some(path);
            }
        }
    }

    #[cfg(target_os = "linux")]
    {
        if let Ok(home) = std::env::var("HOME") {
            let path = PathBuf::from(home).join(".config/microsoft-edge/Default/Cookies");
            if path.exists() {
                return Some(path);
            }
        }
    }

    #[cfg(target_os = "windows")]
    {
        if let Ok(localappdata) = std::env::var("LOCALAPPDATA") {
            let path = PathBuf::from(localappdata)
                .join("Microsoft\\Edge\\User Data\\Default\\Network\\Cookies");
            if path.exists() {
                return Some(path);
            }
        }
    }

    None
}

fn get_firefox_cookie_path() -> Option<PathBuf> {
    #[cfg(target_os = "macos")]
    {
        if let Ok(home) = std::env::var("HOME") {
            let profiles_path =
                PathBuf::from(home).join("Library/Application Support/Firefox/Profiles");
            if profiles_path.exists() {
                if let Ok(entries) = std::fs::read_dir(&profiles_path) {
                    for entry in entries.flatten() {
                        let cookie_path = entry.path().join("cookies.sqlite");
                        if cookie_path.exists() {
                            return Some(cookie_path);
                        }
                    }
                }
            }
        }
    }

    #[cfg(target_os = "linux")]
    {
        if let Ok(home) = std::env::var("HOME") {
            let profiles_path = PathBuf::from(home).join(".mozilla/firefox");
            if profiles_path.exists() {
                if let Ok(entries) = std::fs::read_dir(&profiles_path) {
                    for entry in entries.flatten() {
                        let cookie_path = entry.path().join("cookies.sqlite");
                        if cookie_path.exists() {
                            return Some(cookie_path);
                        }
                    }
                }
            }
        }
    }

    #[cfg(target_os = "windows")]
    {
        if let Ok(appdata) = std::env::var("APPDATA") {
            let profiles_path = PathBuf::from(appdata).join("Mozilla\\Firefox\\Profiles");
            if profiles_path.exists() {
                if let Ok(entries) = std::fs::read_dir(&profiles_path) {
                    for entry in entries.flatten() {
                        let cookie_path = entry.path().join("cookies.sqlite");
                        if cookie_path.exists() {
                            return Some(cookie_path);
                        }
                    }
                }
            }
        }
    }

    None
}

// ==================== Cookie 读取和解密 ====================

fn count_cookies(path: &PathBuf) -> Result<usize, String> {
    let conn = Connection::open(path).map_err(|e| format!("Failed to open database: {}", e))?;

    let table = infer_cookie_table(&conn)?;
    let query = format!("SELECT COUNT(*) FROM {}", table);

    let count: i64 = conn
        .query_row(&query, [], |row| row.get(0))
        .map_err(|e| format!("Query failed: {}", e))?;

    Ok(count as usize)
}

fn infer_cookie_table(conn: &Connection) -> Result<&'static str, String> {
    let result: Result<String, _> = conn.query_row(
        "SELECT name FROM sqlite_master WHERE type='table' AND name='moz_cookies'",
        [],
        |row| row.get(0),
    );
    if result.is_ok() {
        return Ok("moz_cookies");
    }
    Ok("cookies")
}

fn map_chrome_cookie_row(row: &rusqlite::Row) -> rusqlite::Result<CookieEntry> {
    let encrypted_value: Vec<u8> = row.get(1)?;
    Ok(CookieEntry {
        name: row.get(0)?,
        value: decrypt_cookie_value(&encrypted_value),
        domain: row.get(2)?,
        path: row.get(3)?,
        expires: row.get(4)?,
        secure: row.get(5)?,
        httponly: row.get(6)?,
    })
}

fn map_firefox_cookie_row(row: &rusqlite::Row) -> rusqlite::Result<CookieEntry> {
    let value: String = row.get(1)?;
    Ok(CookieEntry {
        name: row.get(0)?,
        value,
        domain: row.get(2)?,
        path: row.get(3)?,
        expires: row.get(4)?,
        secure: row.get(5)?,
        httponly: row.get(6)?,
    })
}

fn read_cookies(path: &PathBuf, domain_filter: Option<String>) -> Result<Vec<CookieEntry>, String> {
    let conn = Connection::open(path).map_err(|e| format!("Failed to open database: {}", e))?;
    let table = infer_cookie_table(&conn)?;

    let (query, param) = if table == "moz_cookies" {
        let base = "SELECT name, value, host, path, expiry, isSecure, isHttpOnly FROM moz_cookies";
        match domain_filter {
            Some(ref domain) => (
                format!("{} WHERE host LIKE ?1", base),
                Some(format!("%{}%", domain)),
            ),
            None => (base.to_string(), None),
        }
    } else {
        let base = "SELECT name, encrypted_value, host_key, path, expires_utc, is_secure, is_httponly FROM cookies";
        match domain_filter {
            Some(ref domain) => (
                format!("{} WHERE host_key LIKE ?1", base),
                Some(format!("%{}%", domain)),
            ),
            None => (base.to_string(), None),
        }
    };

    let mut stmt = conn
        .prepare(&query)
        .map_err(|e| format!("Prepare failed: {}", e))?;

    let mut cookies = Vec::new();

    if table == "moz_cookies" {
        let map_fn = map_firefox_cookie_row;
        if let Some(ref p) = param {
            let mut rows = stmt
                .query_map([p.as_str()], map_fn)
                .map_err(|e| format!("Query failed: {}", e))?;
            while let Some(Ok(c)) = rows.next() {
                cookies.push(c);
            }
        } else {
            let mut rows = stmt
                .query_map([], map_fn)
                .map_err(|e| format!("Query failed: {}", e))?;
            while let Some(Ok(c)) = rows.next() {
                cookies.push(c);
            }
        }
    } else {
        let map_fn = map_chrome_cookie_row;
        if let Some(ref p) = param {
            let mut rows = stmt
                .query_map([p.as_str()], map_fn)
                .map_err(|e| format!("Query failed: {}", e))?;
            while let Some(Ok(c)) = rows.next() {
                cookies.push(c);
            }
        } else {
            let mut rows = stmt
                .query_map([], map_fn)
                .map_err(|e| format!("Query failed: {}", e))?;
            while let Some(Ok(c)) = rows.next() {
                cookies.push(c);
            }
        }
    }

    Ok(cookies)
}

fn decrypt_cookie_value(encrypted: &[u8]) -> String {
    // Chrome v10+ 加密格式: "v10" + nonce (12 bytes) + ciphertext
    if encrypted.len() < 15 {
        return String::from_utf8_lossy(encrypted).to_string();
    }

    // 检查是否是 v10/v11 格式
    if &encrypted[0..3] == b"v10" || &encrypted[0..3] == b"v11" {
        #[cfg(target_os = "windows")]
        {
            return decrypt_windows(&encrypted[3..]);
        }

        #[cfg(target_os = "macos")]
        {
            return decrypt_macos(&encrypted[3..]);
        }

        #[cfg(target_os = "linux")]
        {
            return decrypt_linux(&encrypted[3..]);
        }
    }

    // 旧版本或未加密
    String::from_utf8_lossy(encrypted).to_string()
}

#[cfg(target_os = "windows")]
fn decrypt_windows(encrypted_data: &[u8]) -> String {
    String::from_utf8_lossy(&decrypt_windows_raw(encrypted_data)).to_string()
}

/// DPAPI decrypt bytes directly, preserving raw binary output.
/// Used by Chrome cookie encryption where the decrypted key is raw bytes, not text.
#[cfg(target_os = "windows")]
fn decrypt_windows_raw(encrypted_data: &[u8]) -> Vec<u8> {
    use windows::Win32::Security::Cryptography::{
        CryptUnprotectData, CRYPTPROTECT_UI_FORBIDDEN, CRYPT_INTEGER_BLOB,
    };

    unsafe {
        let data_in = CRYPT_INTEGER_BLOB {
            cbData: encrypted_data.len() as u32,
            pbData: encrypted_data.as_ptr() as *mut u8,
        };

        let mut data_out = CRYPT_INTEGER_BLOB {
            cbData: 0,
            pbData: std::ptr::null_mut(),
        };

        match CryptUnprotectData(
            &data_in,
            None,
            None,
            None,
            None,
            CRYPTPROTECT_UI_FORBIDDEN,
            &mut data_out as *mut _,
        ) {
            Ok(()) => {
                if data_out.pbData.is_null() || data_out.cbData == 0 {
                    return encrypted_data.to_vec();
                }
                std::slice::from_raw_parts(data_out.pbData, data_out.cbData as usize).to_vec()
            }
            Err(_) => encrypted_data.to_vec(),
        }
    }
}

#[cfg(target_os = "macos")]
fn decrypt_macos(encrypted_data: &[u8]) -> String {
    match get_chrome_safe_storage_password() {
        Some(password) => decrypt_chrome_aes_cbc(encrypted_data, &password),
        None => "[Failed to get encryption key from Keychain]".to_string(),
    }
}

#[cfg(target_os = "linux")]
fn decrypt_linux(encrypted_data: &[u8]) -> String {
    match get_chrome_safe_storage_password() {
        Some(password) => decrypt_chrome_aes_cbc(encrypted_data, &password),
        None => "[Failed to get encryption key from keyring]".to_string(),
    }
}

// AES-128-CBC 解密（Chrome macOS/Linux 使用 PBKDF2-SHA1 + AES-128-CBC）
#[cfg(any(target_os = "macos", target_os = "linux"))]
fn decrypt_chrome_aes_cbc(encrypted_data: &[u8], password: &str) -> String {
    use aes::cipher::BlockDecryptMut;
    use aes::Aes128;
    use cbc::cipher::KeyIvInit;
    use pbkdf2::pbkdf2_hmac;
    use sha1::Sha1;

    let mut key = [0u8; 16];
    pbkdf2_hmac::<Sha1>(password.as_bytes(), b"saltysalt", 1003, &mut key);

    let iv = [0x20u8; 16];
    let cipher = cbc::Decryptor::<Aes128>::new(&key.into(), &iv.into());

    let mut buf = encrypted_data.to_vec();
    match cipher.decrypt_padded_mut::<cbc::cipher::block_padding::Pkcs7>(&mut buf) {
        Ok(pt) => String::from_utf8_lossy(pt).to_string(),
        Err(_) => "[Decryption failed]".to_string(),
    }
}

#[cfg(any(target_os = "macos", target_os = "linux"))]
fn get_chrome_safe_storage_password() -> Option<String> {
    #[cfg(target_os = "macos")]
    {
        use keyring::Entry;
        let entry = Entry::new("Chrome Safe Storage", "Chrome");
        if let Ok(entry) = entry {
            if let Ok(password) = entry.get_password() {
                return Some(password);
            }
        }
    }

    #[cfg(target_os = "linux")]
    {
        use keyring::Entry;
        let entry = Entry::new("Chrome Safe Storage", "Chrome");
        if let Ok(entry) = entry {
            if let Ok(password) = entry.get_password() {
                return Some(password);
            }
        }
    }

    #[cfg(target_os = "windows")]
    {
        if let Ok(localappdata) = std::env::var("LOCALAPPDATA") {
            let local_state_path =
                PathBuf::from(localappdata).join("Google\\Chrome\\User Data\\Local State");

            if let Ok(content) = std::fs::read_to_string(&local_state_path) {
                if let Ok(json) = serde_json::from_str::<serde_json::Value>(&content) {
                    if let Some(encoded_key) = json["os_crypt"]["encrypted_key"].as_str() {
                        if let Ok(decoded) = general_purpose::STANDARD.decode(encoded_key) {
                            if decoded.len() >= 5 && &decoded[0..5] == b"DPAPI" {
                                let raw_key = decrypt_windows_raw(&decoded[5..]);
                                // Chrome AES key is 32 raw bytes; wrap via lossy for PBKDF2
                                return Some(String::from_utf8_lossy(&raw_key).into_owned());
                            }
                        }
                    }
                }
            }
        }
    }

    None
}
