use rusqlite::Connection;
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};

/// Chrome Cookie 解密 / 密钥获取核心逻辑（AES-128-CBC、AES-256-GCM、SHA-256 完整性校验）
/// 已拆出到 cookie_crypto 模块，本文件仅保留浏览器发现/路径/导出等命令层逻辑
#[path = "cookie_crypto.rs"]
mod cookie_crypto;

/// 前端展示的最大 Cookie 条数
const MAX_DISPLAY_COOKIES: usize = 500;

#[cfg(test)]
mod tests {
    #[cfg(target_os = "linux")]
    use super::cookie_crypto::try_aes_128_cbc;
    use super::*;
    #[cfg(target_os = "linux")]
    use sha2::{Digest, Sha256};

    #[test]
    fn test_cookie_entry_serialization() {
        let entry = CookieEntry {
            name: "session".to_string(),
            value: "abc123".to_string(),
            domain: ".example.com".to_string(),
            path: "/".to_string(),
            expires: 1700000000,
            secure: true,
            httponly: true,
        };
        let json = serde_json::to_string(&entry).unwrap();
        assert!(json.contains("\"name\":\"session\""));
        assert!(json.contains("\"domain\":\".example.com\""));
    }

    #[test]
    fn test_browser_info_serialization() {
        let info = BrowserInfo {
            name: "Chrome".to_string(),
            cookie_path: "/path/to/Cookies".to_string(),
            cookie_count: 42,
        };
        let json = serde_json::to_string(&info).unwrap();
        assert!(json.contains("\"cookie_count\":42"));
    }

    #[test]
    fn test_export_as_netscape_format() {
        let cookies = vec![
            CookieEntry {
                name: "token".to_string(),
                value: "secret".to_string(),
                domain: ".example.com".to_string(),
                path: "/".to_string(),
                expires: 2000000000,
                secure: true,
                httponly: true,
            },
            CookieEntry {
                name: "non_secure".to_string(),
                value: "val".to_string(),
                domain: ".test.com".to_string(),
                path: "/app".to_string(),
                expires: 0,
                secure: false,
                httponly: false,
            },
        ];
        let mut output = String::from("# Netscape HTTP Cookie File\n");
        output.push_str("# https://curl.haxx.se/docs/http-cookies.html\n");
        output.push_str("# This file was generated by DevNexus\n\n");
        for cookie in &cookies {
            let expires = if cookie.expires > 0 {
                cookie.expires.to_string()
            } else {
                "0".to_string()
            };
            output.push_str(&format!(
                "{}\t{}\t{}\t{}\t{}\t{}\t{}\n",
                cookie.domain,
                if cookie.httponly { "TRUE" } else { "FALSE" },
                cookie.path,
                if cookie.secure { "TRUE" } else { "FALSE" },
                expires,
                cookie.name,
                cookie.value
            ));
        }
        assert!(output.starts_with("# Netscape"));
    }

    #[test]
    fn test_infer_cookie_table_firefox() {
        let conn = Connection::open_in_memory().unwrap();
        conn.execute_batch("CREATE TABLE moz_cookies (id INTEGER);")
            .unwrap();
        let table = infer_cookie_table(&conn).unwrap();
        assert_eq!(table, "moz_cookies");
    }

    #[test]
    fn test_infer_cookie_table_chrome() {
        let conn = Connection::open_in_memory().unwrap();
        conn.execute_batch("CREATE TABLE cookies (id INTEGER);")
            .unwrap();
        let table = infer_cookie_table(&conn).unwrap();
        assert_eq!(table, "cookies");
    }

    #[test]
    fn test_infer_cookie_table_fallback() {
        let conn = Connection::open_in_memory().unwrap();
        let table = infer_cookie_table(&conn).unwrap();
        assert_eq!(table, "cookies");
    }

    #[test]
    fn test_count_cookies_fails_on_missing_db() {
        let path = PathBuf::from("/nonexistent/path/cookies.db");
        let result = count_cookies(&path);
        assert!(result.is_err());
    }

    #[test]
    fn test_map_chrome_cookie_fields() {
        let json = r#"{
            "name": "test",
            "value": "encrypted",
            "domain": ".example.com",
            "path": "/",
            "expires": 1000,
            "secure": false,
            "httponly": false
        }"#;
        let entry: CookieEntry = serde_json::from_str(json).unwrap();
        assert_eq!(entry.name, "test");
        assert_eq!(entry.expires, 1000);
        assert!(!entry.secure);
    }

    #[cfg(target_os = "linux")]
    #[test]
    fn test_try_aes_128_cbc_integrity_check() {
        use aes::cipher::{BlockEncryptMut, KeyIvInit};
        type Aes128CbcEnc = cbc::Encryptor<aes::Aes128>;

        let key = [0x42u8; 16];
        let iv = [0x24u8; 16];
        let host_key = "https://example.com";
        let payload = b"session_token_123";

        // 构造明文: [sha256(host_key) 32B | payload]
        let hash = Sha256::digest(host_key.as_bytes());
        let mut plaintext = Vec::new();
        plaintext.extend_from_slice(&hash);
        plaintext.extend_from_slice(payload);

        let enc = Aes128CbcEnc::new_from_slices(&key, &iv).unwrap();
        let mut out_buf = vec![0u8; plaintext.len() + 16];
        let ciphertext = enc
            .encrypt_padded_b2b_mut::<aes::cipher::block_padding::Pkcs7>(&plaintext, &mut out_buf)
            .unwrap()
            .to_vec();

        // 正常: 哈希匹配 → Ok(payload)
        let result = try_aes_128_cbc(&key, &iv, &ciphertext, host_key, true);
        assert_eq!(result, Ok("session_token_123".to_string()));

        // 篡改: 明文前 32 字节哈希被改 → Err("Integrity check failed")
        let mut tampered = plaintext.clone();
        tampered[0] ^= 0xff;
        let enc2 = Aes128CbcEnc::new_from_slices(&key, &iv).unwrap();
        let mut tampered_buf = vec![0u8; tampered.len() + 16];
        let tampered_ciphertext = enc2
            .encrypt_padded_b2b_mut::<aes::cipher::block_padding::Pkcs7>(
                &tampered,
                &mut tampered_buf,
            )
            .unwrap()
            .to_vec();
        let result = try_aes_128_cbc(&key, &iv, &tampered_ciphertext, host_key, true);
        assert!(result.is_err());

        // 空密文 → Err
        assert!(try_aes_128_cbc(&key, &iv, &[], host_key, true).is_err());
    }

    #[test]
    fn test_make_cookie_tmp_path_unique_and_suffixed() {
        let a = make_cookie_tmp_path();
        let b = make_cookie_tmp_path();
        // 随机后缀（纳秒时间戳）应保证两次调用返回不同路径
        assert_ne!(a, b);
        // 路径非空，且文件名包含 pid 与 .sqlite 后缀
        let fname = a.file_name().unwrap().to_string_lossy().to_string();
        assert!(!fname.is_empty());
        assert!(fname.contains(&std::process::id().to_string()));
        assert!(fname.ends_with(".sqlite"));
    }

    #[test]
    fn test_temp_cookie_cleanup_removes_files() {
        let tmp_path = make_cookie_tmp_path();
        std::fs::write(&tmp_path, b"main").unwrap();
        std::fs::write(tmp_path.with_extension("sqlite-wal"), b"wal").unwrap();
        std::fs::write(tmp_path.with_extension("sqlite-shm"), b"shm").unwrap();
        std::fs::write(tmp_path.with_extension("sqlite-journal"), b"journal").unwrap();
        {
            let _cleanup = TempCookieCleanup(tmp_path.clone());
            assert!(tmp_path.exists());
        }
        // guard drop 后主文件与 wal/shm/journal 辅助文件全部被清理
        assert!(!tmp_path.exists());
        assert!(!tmp_path.with_extension("sqlite-wal").exists());
        assert!(!tmp_path.with_extension("sqlite-shm").exists());
        assert!(!tmp_path.with_extension("sqlite-journal").exists());
    }

    #[cfg(unix)]
    #[test]
    fn test_temp_cookie_permissions_0600() {
        use std::os::unix::fs::PermissionsExt;
        let tmp_path = make_cookie_tmp_path();
        std::fs::write(&tmp_path, b"cookie").unwrap();
        let _cleanup = TempCookieCleanup(tmp_path.clone());
        // 复刻 read_cookies 中的收紧权限逻辑
        let _ = std::fs::set_permissions(&tmp_path, std::fs::Permissions::from_mode(0o600));
        let mode = std::fs::metadata(&tmp_path).unwrap().permissions().mode() & 0o777;
        assert_eq!(mode, 0o600);
    }
}

#[derive(Serialize, Deserialize, Clone)]
pub struct CookieEntry {
    pub name: String,
    pub value: String,
    pub domain: String,
    pub path: String,
    pub expires: i64,
    pub secure: bool,
    pub httponly: bool,
}

#[derive(Serialize, Deserialize)]
pub struct BrowserInfo {
    pub name: String,
    pub cookie_path: String,
    pub cookie_count: usize,
}

/// 获取支持的浏览器列表
#[tauri::command]
pub fn get_supported_browsers() -> Vec<BrowserInfo> {
    let mut browsers = Vec::new();

    // Chrome
    if let Some(path) = get_chrome_cookie_path() {
        let count = count_cookies(&path).unwrap_or(0);
        browsers.push(BrowserInfo {
            name: "Chrome".to_string(),
            cookie_path: path.to_string_lossy().to_string(),
            cookie_count: count,
        });
    }

    // Edge
    if let Some(path) = get_edge_cookie_path() {
        let count = count_cookies(&path).unwrap_or(0);
        browsers.push(BrowserInfo {
            name: "Edge".to_string(),
            cookie_path: path.to_string_lossy().to_string(),
            cookie_count: count,
        });
    }

    // Firefox
    if let Some(path) = get_firefox_cookie_path() {
        let count = count_cookies(&path).unwrap_or(0);
        browsers.push(BrowserInfo {
            name: "Firefox".to_string(),
            cookie_path: path.to_string_lossy().to_string(),
            cookie_count: count,
        });
    }

    browsers
}

/// 提取指定浏览器的 Cookie
#[tauri::command]
pub fn extract_cookies(
    browser_name: String,
    domain_filter: Option<String>,
    max_results: Option<usize>,
) -> Result<Vec<CookieEntry>, String> {
    let cookie_path = match browser_name.as_str() {
        "Chrome" => get_chrome_cookie_path(),
        "Edge" => get_edge_cookie_path(),
        "Firefox" => get_firefox_cookie_path(),
        _ => return Err(format!("Unsupported browser: {}", browser_name)),
    };

    let path = cookie_path.ok_or_else(|| format!("{} cookie database not found", browser_name))?;

    if !path.exists() {
        return Err(format!("Cookie database does not exist: {:?}", path));
    }

    // 前端调用时 None → 默认 500 条限制，防止 IPC 数据过大导致崩溃
    let limit = max_results.unwrap_or(MAX_DISPLAY_COOKIES);
    let cookies = read_cookies(&path, domain_filter, Some(limit))?;
    Ok(cookies)
}

/// 导出为 Netscape Cookie 格式（curl/wget 兼容）
#[tauri::command]
pub fn export_as_netscape(
    browser_name: String,
    domain_filter: Option<String>,
) -> Result<String, String> {
    let path = get_browser_cookie_path(&browser_name)?;
    let cookies = read_cookies(&path, domain_filter, None)?;

    let mut output = String::from("# Netscape HTTP Cookie File\n");
    output.push_str("# https://curl.haxx.se/docs/http-cookies.html\n");
    output.push_str("# This file was generated by DevNexus\n\n");

    for cookie in cookies {
        let expires = if cookie.expires > 0 {
            cookie.expires.to_string()
        } else {
            "0".to_string()
        };

        output.push_str(&format!(
            "{}\t{}\t{}\t{}\t{}\t{}\t{}\n",
            cookie.domain,
            if cookie.httponly { "TRUE" } else { "FALSE" },
            cookie.path,
            if cookie.secure { "TRUE" } else { "FALSE" },
            expires,
            cookie.name,
            cookie.value
        ));
    }

    Ok(output)
}

/// 导出为 JSON 格式
#[tauri::command]
pub fn export_as_json(
    browser_name: String,
    domain_filter: Option<String>,
) -> Result<String, String> {
    let path = get_browser_cookie_path(&browser_name)?;
    let cookies = read_cookies(&path, domain_filter, None)?;
    serde_json::to_string_pretty(&cookies).map_err(|e| e.to_string())
}

// ==================== 浏览器 Cookie 路径检测 ====================

/// 根据浏览器名称获取 Cookie 数据库路径（供导出函数使用）
fn get_browser_cookie_path(browser_name: &str) -> Result<PathBuf, String> {
    let path = match browser_name {
        "Chrome" => get_chrome_cookie_path(),
        "Edge" => get_edge_cookie_path(),
        "Firefox" => get_firefox_cookie_path(),
        _ => return Err(format!("Unsupported browser: {}", browser_name)),
    };
    path.ok_or_else(|| format!("{} cookie database not found", browser_name))
}

fn get_chrome_cookie_path() -> Option<PathBuf> {
    #[cfg(target_os = "macos")]
    {
        if let Ok(home) = std::env::var("HOME") {
            let path = PathBuf::from(home)
                .join("Library/Application Support/Google/Chrome/Default/Cookies");
            if path.exists() {
                return Some(path);
            }
        }
    }

    #[cfg(target_os = "linux")]
    {
        if let Ok(home) = std::env::var("HOME") {
            let path = PathBuf::from(home).join(".config/google-chrome/Default/Cookies");
            if path.exists() {
                return Some(path);
            }
        }
    }

    #[cfg(target_os = "windows")]
    {
        if let Ok(localappdata) = std::env::var("LOCALAPPDATA") {
            let path = PathBuf::from(localappdata)
                .join("Google\\Chrome\\User Data\\Default\\Network\\Cookies");
            if path.exists() {
                return Some(path);
            }
        }
    }

    // 检查 Chromium
    if let Ok(ref home) = std::env::var("HOME") {
        let path = PathBuf::from(home).join(".config/chromium/Default/Cookies");
        if path.exists() {
            return Some(path);
        }
        // Snap 安装的 Chromium
        let snap_path =
            PathBuf::from(home).join("snap/chromium/current/.config/chromium/Default/Cookies");
        if snap_path.exists() {
            return Some(snap_path);
        }
    }

    None
}

fn get_edge_cookie_path() -> Option<PathBuf> {
    #[cfg(target_os = "macos")]
    {
        if let Ok(home) = std::env::var("HOME") {
            let path = PathBuf::from(home)
                .join("Library/Application Support/Microsoft Edge/Default/Cookies");
            if path.exists() {
                return Some(path);
            }
        }
    }

    #[cfg(target_os = "linux")]
    {
        if let Ok(home) = std::env::var("HOME") {
            let path = PathBuf::from(home).join(".config/microsoft-edge/Default/Cookies");
            if path.exists() {
                return Some(path);
            }
        }
    }

    #[cfg(target_os = "windows")]
    {
        if let Ok(localappdata) = std::env::var("LOCALAPPDATA") {
            let path =
                PathBuf::from(localappdata).join("Microsoft\\Edge\\User Data\\Default\\Cookies");
            if path.exists() {
                return Some(path);
            }
        }
    }

    None
}

fn get_firefox_cookie_path() -> Option<PathBuf> {
    let home = std::env::var("HOME").ok()?;
    let profile_root = PathBuf::from(&home).join(".mozilla/firefox");

    if !profile_root.exists() {
        return None;
    }

    // 读取 profiles.ini 找到默认 profile
    let profiles_ini = profile_root.join("profiles.ini");
    if profiles_ini.exists() {
        if let Ok(content) = std::fs::read_to_string(&profiles_ini) {
            let mut current_path: Option<String> = None;
            let mut is_default = false;
            for line in content.lines() {
                let line = line.trim();
                if line.to_lowercase() == "[profile0]" || line.starts_with("[profile") {
                    current_path = None;
                    is_default = false;
                } else if let Some(val) = line.strip_prefix("Path=") {
                    current_path = Some(val.to_string());
                } else if line.to_lowercase() == "default=1" || line.starts_with("Default=") {
                    is_default = true;
                }
                // Section break — evaluate
                if line.is_empty() || (line.starts_with('[') && current_path.is_some()) {
                    if is_default {
                        if let Some(ref path) = current_path {
                            let cookie_path = if path.starts_with('/') {
                                PathBuf::from(path)
                            } else {
                                profile_root.join(path)
                            }
                            .join("cookies.sqlite");
                            if cookie_path.exists() {
                                return Some(cookie_path);
                            }
                        }
                    }
                    if line.starts_with('[') && line != "[Profile0]" {
                        current_path = None;
                        is_default = false;
                    }
                }
            }
            // Check last section
            if is_default {
                if let Some(ref path) = current_path {
                    let cookie_path = if path.starts_with('/') {
                        PathBuf::from(path)
                    } else {
                        profile_root.join(path)
                    }
                    .join("cookies.sqlite");
                    if cookie_path.exists() {
                        return Some(cookie_path);
                    }
                }
            }
        }
    }

    // 回退：扫描 profile 目录
    if let Ok(entries) = std::fs::read_dir(&profile_root) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                let cookie_path = path.join("cookies.sqlite");
                if cookie_path.exists() {
                    return Some(cookie_path);
                }
            }
        }
    }

    None
}

// ==================== Cookie 数据库操作 ====================

fn count_cookies(path: &PathBuf) -> Result<usize, String> {
    let conn = Connection::open(path).map_err(|e| format!("Failed to open: {}", e))?;
    let table = infer_cookie_table(&conn)?;
    let count: usize = conn
        .query_row(&format!("SELECT COUNT(*) FROM {}", table), [], |row| {
            row.get(0)
        })
        .map_err(|e| format!("Count failed: {}", e))?;
    Ok(count)
}

fn infer_cookie_table(conn: &Connection) -> Result<&'static str, String> {
    let tables: Vec<String> = conn
        .prepare("SELECT name FROM sqlite_master WHERE type='table'")
        .map_err(|e| format!("Query failed: {}", e))?
        .query_map([], |row| row.get(0))
        .map_err(|e| format!("Query failed: {}", e))?
        .filter_map(|r| r.ok())
        .collect();

    if tables.iter().any(|t| t == "moz_cookies") {
        Ok("moz_cookies")
    } else {
        Ok("cookies")
    }
}

/// 获取 Cookie 数据库的版本号（用于判断是否包含完整性检查哈希）
fn get_cookie_db_version(path: &Path) -> i32 {
    if let Ok(conn) = Connection::open(path) {
        if let Ok(version) =
            conn.query_row("SELECT value FROM meta WHERE key='version'", [], |row| {
                row.get::<_, i32>(0)
            })
        {
            return version;
        }
    }
    0
}

fn map_chrome_cookie_row(
    row: &rusqlite::Row,
    has_integrity_check: bool,
) -> rusqlite::Result<CookieEntry> {
    let encrypted_value: Vec<u8> = row.get(1)?;
    let host_key: String = row.get(2)?;
    let expires_utc: i64 = row.get(4)?;
    // Chrome 的 expires_utc 是微秒（microseconds）从 1601-01-01（WebKit epoch）
    // 转换为 Unix 秒数（从 1970-01-01）
    // 偏移量：11644473600 秒（1601 → 1970），微秒 → 秒 ÷ 1_000_000
    let expires = if expires_utc == 0 {
        0 // session cookie
    } else {
        let unix_micros = expires_utc - 11_644_473_600_000_000i64;
        let unix_secs = unix_micros / 1_000_000;
        if unix_secs > 0 {
            unix_secs
        } else {
            0
        }
    };
    Ok(CookieEntry {
        name: row.get(0)?,
        value: cookie_crypto::decrypt_cookie_value(
            &encrypted_value,
            &host_key,
            has_integrity_check,
        )
        .map_err(|e| {
            rusqlite::Error::FromSqlConversionFailure(
                1,
                rusqlite::types::Type::Blob,
                Box::new(std::io::Error::other(e)),
            )
        })?,
        domain: host_key,
        path: row.get(3)?,
        expires,
        secure: row.get(5)?,
        httponly: row.get(6)?,
    })
}

fn map_firefox_cookie_row(row: &rusqlite::Row) -> rusqlite::Result<CookieEntry> {
    let value: String = row.get(1)?;
    Ok(CookieEntry {
        name: row.get(0)?,
        value,
        domain: row.get(2)?,
        path: row.get(3)?,
        expires: row.get(4)?,
        secure: row.get(5)?,
        httponly: row.get(6)?,
    })
}

/// 生成带随机后缀的 Cookie 临时文件路径（pid + 纳秒时间戳 + 原子计数器），
/// 避免固定文件名（如 cookies_{pid}.sqlite）被同机其他用户预测路径后读取。
/// 计数器保证同一进程内多次调用（含并行测试/并发请求）路径绝对不重复——
/// 某些平台 SystemTime 分辨率较粗，仅靠时间戳会在同 tick 内生成相同路径，
/// 导致并行测试互相删除对方的临时文件（CI 上偶发失败）。
fn make_cookie_tmp_path() -> std::path::PathBuf {
    use std::sync::atomic::{AtomicU64, Ordering};
    static COUNTER: AtomicU64 = AtomicU64::new(0);
    let tmp_dir = std::env::temp_dir().join("devnexus_cookies");
    let _ = std::fs::create_dir_all(&tmp_dir);
    tmp_dir.join(format!(
        "cookies_{}_{}_{}.sqlite",
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_nanos())
            .unwrap_or(0),
        COUNTER.fetch_add(1, Ordering::Relaxed)
    ))
}

/// Cookie 临时文件清理 guard（RAII）：
/// drop 时删除主文件及 wal/shm/journal 辅助文件，覆盖成功与失败（? 提前返回）路径
struct TempCookieCleanup(std::path::PathBuf);

impl Drop for TempCookieCleanup {
    fn drop(&mut self) {
        let _ = std::fs::remove_file(&self.0);
        let _ = std::fs::remove_file(self.0.with_extension("sqlite-wal"));
        let _ = std::fs::remove_file(self.0.with_extension("sqlite-shm"));
        let _ = std::fs::remove_file(self.0.with_extension("sqlite-journal"));
    }
}

fn read_cookies(
    path: &PathBuf,
    domain_filter: Option<String>,
    max_results: Option<usize>,
) -> Result<Vec<CookieEntry>, String> {
    // 复制到临时文件再打开，避免浏览器锁定数据库导致 "database is locked"
    // 临时文件使用随机名（pid + 纳秒时间戳），防止固定名被同机其他用户预测/读取
    let tmp_path = make_cookie_tmp_path();
    // RAII guard：无论 read_cookies 成功还是失败（含 ? 提前返回），
    // 返回时自动删除主文件及 wal/shm/journal 辅助文件
    let _cleanup = TempCookieCleanup(tmp_path.clone());
    // 删除残留文件
    let _ = std::fs::remove_file(&tmp_path);
    let _ = std::fs::remove_file(tmp_path.with_extension("sqlite-wal"));
    let _ = std::fs::remove_file(tmp_path.with_extension("sqlite-shm"));
    let _ = std::fs::remove_file(tmp_path.with_extension("sqlite-journal"));

    std::fs::copy(path, &tmp_path)
        .map_err(|e| format!("Failed to copy cookie database: {} (path: {:?})", e, path))?;

    // 复制后收紧权限（Unix）：0600，防止同机其他用户读取浏览器 Cookie
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let _ = std::fs::set_permissions(&tmp_path, std::fs::Permissions::from_mode(0o600));
    }

    // 复制 SQLite 辅助文件（WAL 或 journal 模式），保证数据一致性
    // Chrome 实际辅助文件格式: Cookies-wal, Cookies-shm, Cookies-journal（拼接后缀，非替换扩展名）
    if let (Some(parent), Some(filename)) = (path.parent(), path.file_name()) {
        let fname = filename.to_string_lossy();

        // WAL 模式: Cookies-wal, Cookies-shm
        let wal_path = parent.join(format!("{}-wal", fname));
        if wal_path.exists() {
            let _ = std::fs::copy(&wal_path, tmp_path.with_extension("sqlite-wal"));
            let shm_path = parent.join(format!("{}-shm", fname));
            if shm_path.exists() {
                let _ = std::fs::copy(&shm_path, tmp_path.with_extension("sqlite-shm"));
            }
        }

        // Journal 模式: Cookies-journal
        let journal_path = parent.join(format!("{}-journal", fname));
        if journal_path.exists() {
            let _ = std::fs::copy(&journal_path, tmp_path.with_extension("sqlite-journal"));
        }
    }

    // 判断是否需要完整性检查（数据库版本 >= 24 表示有 v11 格式的完整性检查）
    // 从临时副本读取版本，避免浏览器锁定原库
    let has_integrity_check = get_cookie_db_version(&tmp_path) >= 24;

    let conn =
        Connection::open(&tmp_path).map_err(|e| format!("Failed to open database: {}", e))?;
    let table = infer_cookie_table(&conn)?;

    // 根据 max_results 生成 LIMIT 子句
    let limit_clause = match max_results {
        Some(n) => format!(" LIMIT {}", n),
        None => String::new(),
    };

    let (query, param) = if table == "moz_cookies" {
        let base = "SELECT name, value, host, path, expiry, isSecure, isHttpOnly FROM moz_cookies";
        match domain_filter {
            Some(ref domain) => (
                format!("{} WHERE host LIKE ?1{}", base, limit_clause),
                Some(format!("%{}%", domain)),
            ),
            None => (format!("{}{}", base, limit_clause), None),
        }
    } else {
        let base = "SELECT name, encrypted_value, host_key, path, expires_utc, is_secure, is_httponly FROM cookies";
        match domain_filter {
            Some(ref domain) => (
                format!("{} WHERE host_key LIKE ?1{}", base, limit_clause),
                Some(format!("%{}%", domain)),
            ),
            None => (format!("{}{}", base, limit_clause), None),
        }
    };

    let mut stmt = conn
        .prepare(&query)
        .map_err(|e| format!("Prepare failed: {}", e))?;

    let mut cookies = Vec::new();

    if table == "moz_cookies" {
        let map_fn = map_firefox_cookie_row;
        if let Some(ref p) = param {
            let rows = stmt
                .query_map([p.as_str()], map_fn)
                .map_err(|e| format!("Query failed: {}", e))?;
            for row in rows {
                cookies.push(row.map_err(|e| format!("Cookie row error: {}", e))?);
            }
        } else {
            let rows = stmt
                .query_map([], map_fn)
                .map_err(|e| format!("Query failed: {}", e))?;
            for row in rows {
                cookies.push(row.map_err(|e| format!("Cookie row error: {}", e))?);
            }
        }
    } else {
        // Chrome/Edge — 传递 has_integrity_check 到 map 闭包
        if let Some(ref p) = param {
            let rows = stmt
                .query_map([p.as_str()], |row| {
                    map_chrome_cookie_row(row, has_integrity_check)
                })
                .map_err(|e| format!("Query failed: {}", e))?;
            for row in rows {
                cookies.push(row.map_err(|e| format!("Cookie row error: {}", e))?);
            }
        } else {
            let rows = stmt
                .query_map([], |row| map_chrome_cookie_row(row, has_integrity_check))
                .map_err(|e| format!("Query failed: {}", e))?;
            for row in rows {
                cookies.push(row.map_err(|e| format!("Cookie row error: {}", e))?);
            }
        }
    }

    Ok(cookies)
}
